// Generated by generate.py; code points are stable, glyph IDs are resolved at load.
package default_icons

Name :: enum {
	Close,
	Up,
	Down,
	Left,
	Right,
	Plus,
	Minus,
	More,
	Check,
	Search,
}

@(private)
codepoints := [Name]rune{
	.Close = '\uE000',
	.Up = '\uE001',
	.Down = '\uE002',
	.Left = '\uE003',
	.Right = '\uE004',
	.Plus = '\uE005',
	.Minus = '\uE006',
	.More = '\uE007',
	.Check = '\uE008',
	.Search = '\uE009',
}
