#!/usr/bin/env python3
"""Build the checked-in font/catalog from original filled SVG outlines.

Regeneration only: python -m pip install fonttools==4.60.1
Normal Odin builds do not execute this script or need Python.
"""
import json
from pathlib import Path
import xml.etree.ElementTree as ET

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.pens.cu2quPen import Cu2QuPen
from fontTools.pens.transformPen import TransformPen
from fontTools.svgLib.path import parse_path

ROOT = Path(__file__).resolve().parent
manifest = json.loads((ROOT / "manifest.json").read_text())
assert len(set(manifest.values())) == len(manifest)
names = [".notdef", *manifest]
glyphs = {}
metrics = {}
for name in names:
    pen = TTGlyphPen(None)
    if name != ".notdef":
        svg = ET.parse(ROOT / "src" / f"{name}.svg").getroot()
        assert svg.attrib["viewBox"] == "0 0 24 24"
        # SVG y-down to TrueType y-up, with 24 grid units per em.
        transformed = TransformPen(Cu2QuPen(pen, 0.5, reverse_direction=False),
                                   (40, 0, 0, -40, 0, 960))
        for element in svg:
            assert element.tag.endswith("}path")
            parse_path(element.attrib["d"], transformed)
    glyphs[name] = pen.glyph()
    glyphs[name].recalcBounds(None)
    metrics[name] = (960, getattr(glyphs[name], "xMin", 0))

font = FontBuilder(960, isTTF=True)
font.setupGlyphOrder(names)
font.setupCharacterMap({int(code, 16): name for name, code in manifest.items()})
font.setupGlyf(glyphs)
font.setupHorizontalMetrics(metrics)
font.setupHorizontalHeader(ascent=960, descent=0)
font.setupNameTable({"familyName": "Rebuilder Icons", "styleName": "Regular",
                    "uniqueFontIdentifier": "RebuilderIcons-Regular-1",
                    "fullName": "Rebuilder Icons Regular", "psName": "RebuilderIcons-Regular",
                    "version": "Version 1.000", "copyright": "Original icons created by Codex for odin-ui-rebuilder."})
font.setupOS2(sTypoAscender=960, sTypoDescender=0, usWinAscent=960, usWinDescent=0)
font.setupPost()
font.setupMaxp()
font.font["head"].created = font.font["head"].modified = 3786912000
font.font.recalcTimestamp = False
font.save(ROOT / "icons.ttf")

catalog = ["// Generated by generate.py; code points are stable, glyph IDs are resolved at load.",
           "package default_icons", "", "Name :: enum {"]
catalog.extend(f"\t{name.title()}," for name in manifest)
catalog.extend(["}", "", "@(private)", "codepoints := [Name]rune{"])
catalog.extend(f"\t.{name.title()} = '\\u{code}'," for name, code in manifest.items())
catalog.extend(["}", ""])
(ROOT / "catalog.odin").write_text("\n".join(catalog))
print(f"Generated {len(manifest)} icons: {(ROOT / 'icons.ttf').stat().st_size} bytes")
