package platform

import "base:runtime"
import "core:strings"
import "core:sys/posix"
import "core:time"

@(private) Clipboard_Offer :: struct {proxy: rawptr, mime: cstring}
@(private) Clipboard_Write :: struct {fd: posix.FD, text: string, offset: int, start: time.Tick}
@(private) Wayland_Clipboard :: struct {
	manager, device, selection: rawptr,
	offers: [dynamic]Clipboard_Offer,
	serial: u32,
}
@(private) clipboard_source: rawptr
@(private) clipboard_text: string
@(private) clipboard_context: runtime.Context
@(private) clipboard_writes: [dynamic]Clipboard_Write

@(private)
ensure_wayland_clipboard :: proc(w: ^Wayland_Window) {
	c := &w.clipboard
	if c.manager == nil || w.seat == nil || c.device != nil { return }
	c.device = wl_construct(c.manager, 1, &wl_data_device_interface, []WL_Argument{{o = nil}, {o = w.seat}})
	wl_listen(c.device, &data_device_listener, w)
}
@(private)
destroy_wayland_clipboard_device :: proc(w: ^Wayland_Window) {
	c := &w.clipboard
	for offer in c.offers { wl_release(offer.proxy, 2) }
	delete(c.offers); c.offers = nil
	// Negotiated data-device version 1 has no release request.
	if c.device != nil { wl_proxy_destroy(c.device) }
	c.device, c.selection, c.serial = nil, nil, 0
}
@(private)
destroy_wayland_clipboard :: proc(w: ^Wayland_Window) {
	destroy_wayland_clipboard_device(w)
	if w.clipboard.manager != nil { wl_proxy_destroy(w.clipboard.manager) }
	w.clipboard = {}
}
@(private)
shutdown_wayland_clipboard :: proc() {
	wl_release(clipboard_source, 1); clipboard_source = nil
	delete(clipboard_text); clipboard_text = ""
	for transfer in clipboard_writes { posix.close(transfer.fd); delete(transfer.text) }
	delete(clipboard_writes); clipboard_writes = nil
}
@(private)
clipboard_window :: proc() -> ^Wayland_Window {
	for record in windows {
		if record != nil && record.native != nil {
			w := cast(^Wayland_Window)record.native
			if w.keyboard_focused && w.clipboard.device != nil { return w }
		}
	}
	return nil
}
@(private)
wayland_clipboard_write :: proc(value: string) -> bool {
	w := clipboard_window()
	if w == nil || w.clipboard.serial == 0 { return false }
	wl_release(clipboard_source, 1)
	delete(clipboard_text); clipboard_text = strings.clone(value)
	clipboard_context = context
	clipboard_source = wl_construct(w.clipboard.manager, 0, &wl_data_source_interface, []WL_Argument{{o = nil}})
	wl_listen(clipboard_source, &data_source_listener, nil)
	wl_request(clipboard_source, 0, []WL_Argument{{s = "text/plain;charset=utf-8"}})
	wl_request(clipboard_source, 0, []WL_Argument{{s = "text/plain"}})
	wl_request(w.clipboard.device, 1, []WL_Argument{{o = clipboard_source}, {u = w.clipboard.serial}})
	wl_display_flush(wayland_display)
	return true
}
@(private)
wayland_clipboard_read :: proc() -> (string, bool) {
	w := clipboard_window()
	if w == nil { return "", false }
	if clipboard_source != nil { return strings.clone(clipboard_text), true }
	mime: cstring
	for offer in w.clipboard.offers { if offer.proxy == w.clipboard.selection { mime = offer.mime; break } }
	if mime == nil { return "", false }
	fds: [2]posix.FD
	if posix.pipe(&fds) != nil { return "", false }
	defer posix.close(fds[0])
	posix.fcntl(fds[0], .SETFL, posix.O_NONBLOCK)
	wl_request(w.clipboard.selection, 1, []WL_Argument{{s = mime}, {i = i32(fds[1])}})
	posix.close(fds[1])
	wl_display_flush(wayland_display)
	bytes: [dynamic]u8
	defer delete(bytes)
	start := time.tick_now()
	for time.tick_since(start) < time.Second {
		buffer: [16384]u8
		n := posix.read(fds[0], raw_data(buffer[:]), len(buffer))
		if n == 0 { return strings.clone(string(bytes[:])), true }
		if n > 0 {
			if len(bytes) + int(n) > 16 * 1024 * 1024 { return "", false }
			append(&bytes, ..buffer[:n]); continue
		}
		if posix.errno() != .EAGAIN && posix.errno() != .EINTR { return "", false }
		// Dispatch protocol callbacks only; never reenter builders or free windows
		// while clipboard_read is called from an application's update.
		wayland_poll(1)
		if wl_display_dispatch_pending(wayland_display) < 0 { return "", false }
		flush_clipboard_writes()
	}
	return "", false
}

// Nonblocking sends avoid deadlocking the display loop on large selections.
// Block/consume only the SIGPIPE generated by this write, preserving the caller's
// signal mask and any previously pending signal.
@(private)
clipboard_pipe_write :: proc(fd: posix.FD, bytes: []u8) -> int {
	mask, old, pending: posix.sigset_t
	posix.sigemptyset(&mask); posix.sigaddset(&mask, .SIGPIPE)
	if posix.pthread_sigmask(.BLOCK, &mask, &old) != .NONE { return -1 }
	defer posix.pthread_sigmask(.SETMASK, &old, nil)
	posix.sigpending(&pending)
	n := posix.write(fd, raw_data(bytes), uint(len(bytes)))
	error := posix.errno()
	defer posix.set_errno(error)
	if n < 0 && posix.errno() == .EPIPE && posix.sigismember(&pending, .SIGPIPE) == 0 {
		posix.sigpending(&pending)
		if posix.sigismember(&pending, .SIGPIPE) != 0 { signal: posix.Signal; posix.sigwait(&mask, &signal) }
	}
	return int(n)
}
@(private)
flush_clipboard_writes :: proc() {
	for i := len(clipboard_writes) - 1; i >= 0; i -= 1 {
		transfer := &clipboard_writes[i]
		n := clipboard_pipe_write(transfer.fd, transmute([]u8)transfer.text[transfer.offset:])
		if n > 0 { transfer.offset += n }
		failed := n < 0 && posix.errno() != .EAGAIN && posix.errno() != .EINTR
		if transfer.offset == len(transfer.text) || failed || time.tick_since(transfer.start) > 5 * time.Second {
			posix.close(transfer.fd); delete(transfer.text)
			clipboard_writes[i] = clipboard_writes[len(clipboard_writes) - 1]
			resize(&clipboard_writes, len(clipboard_writes) - 1)
		}
	}
}

@(private)
data_offer :: proc "c" (data, _: rawptr, proxy: rawptr) {
	w := cast(^Wayland_Window)data; context = w.odin_context
	append(&w.clipboard.offers, Clipboard_Offer{proxy = proxy})
	wl_listen(proxy, &data_offer_listener, w)
}
@(private)
offer_mime :: proc "c" (data, proxy: rawptr, mime: cstring) {
	w := cast(^Wayland_Window)data
	for &offer in w.clipboard.offers {
		if offer.proxy == proxy {
			if string(mime) == "text/plain;charset=utf-8" { offer.mime = "text/plain;charset=utf-8" }
			else if string(mime) == "text/plain" && offer.mime == nil { offer.mime = "text/plain" }
		}
	}
}
@(private)
drop_clipboard_offer :: proc(w: ^Wayland_Window, proxy: rawptr) {
	for offer, i in w.clipboard.offers {
		if offer.proxy == proxy {
			wl_release(proxy, 2)
			w.clipboard.offers[i] = w.clipboard.offers[len(w.clipboard.offers) - 1]
			resize(&w.clipboard.offers, len(w.clipboard.offers) - 1); return
		}
	}
}
@(private)
data_selection :: proc "c" (data, _: rawptr, proxy: rawptr) {
	w := cast(^Wayland_Window)data; context = w.odin_context
	if w.clipboard.selection != proxy { drop_clipboard_offer(w, w.clipboard.selection) }
	w.clipboard.selection = proxy
}
@(private)
data_enter :: proc "c" (data, _: rawptr, _: u32, _: rawptr, _, _: i32, offer: rawptr) {
	w := cast(^Wayland_Window)data; context = w.odin_context
	// Drag-and-drop is not part of the clipboard API.
	drop_clipboard_offer(w, offer)
}
@(private) data_leave :: proc "c" (_: rawptr, _: rawptr) {}
@(private) data_motion :: proc "c" (_: rawptr, _: rawptr, _: u32, _, _: i32) {}
@(private) data_drop :: proc "c" (_: rawptr, _: rawptr) {}
@(private) source_target :: proc "c" (_: rawptr, _: rawptr, _: cstring) {}
@(private)
source_send :: proc "c" (_: rawptr, source: rawptr, _: cstring, fd: i32) {
	context = clipboard_context
	if source != clipboard_source { posix.close(posix.FD(fd)); return }
	posix.fcntl(posix.FD(fd), .SETFL, posix.O_NONBLOCK)
	append(&clipboard_writes, Clipboard_Write{fd = posix.FD(fd), text = strings.clone(clipboard_text), start = time.tick_now()})
}
@(private)
source_cancelled :: proc "c" (_: rawptr, source: rawptr) {
	context = clipboard_context
	if source == clipboard_source {
		wl_release(source, 1); clipboard_source = nil
		delete(clipboard_text); clipboard_text = ""
	}
}

data_offer_listener := struct {offer: type_of(offer_mime)}{offer_mime}
data_device_listener := struct {
	offer: type_of(data_offer), enter: type_of(data_enter), leave: type_of(data_leave),
	motion: type_of(data_motion), drop: type_of(data_drop), selection: type_of(data_selection),
}{data_offer, data_enter, data_leave, data_motion, data_drop, data_selection}
data_source_listener := struct {target: type_of(source_target), send: type_of(source_send), cancelled: type_of(source_cancelled)}{source_target, source_send, source_cancelled}
